name: CI/CD Pipeline

on:
  push:
    branches:
      - "*"

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Tjek kode ud
        uses: actions/checkout@v3

      - name: Opsæt JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Byg med Maven
        env:
          DEV_DATABASE_URL: ${{ secrets.DB_URL }}
          DEV_USERNAME: ${{ secrets.DB_USERNAME }}
          DEV_PASSWORD: ${{ secrets.DB_PASSWORD }}
        
        run: mvn clean package

      - name: Kør tests
        run: mvn test

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: java-app  
          path: target/*.jar  

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Tjek kode ud
        uses: actions/checkout@v3

      - name: Download artefakt
        uses: actions/download-artifact@v4
        with:
          name: java-app 

      - name: Login til Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy til Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'WishlistprojectARE'
          slot-name: 'Production'
          package: 'target/*.jar'  
